---
- hosts: localhost

  vars:
    username:   "admin"
    password:   "some_password" 
    ip:         "some_ip"
    

  tasks:
   - name: ilo accounts
     ilo_user_facts:
        ilo_ip        : "{{ ip }}"
        ilo_username  : "{{ username }}"
        ilo_password  : "{{ password }}"
        type:       'UserName'
        name: 'dhk'
     no_log: true
     register: result

   - debug: var=result['user']
