---
- hosts: localhost

  vars:
    ip:         10.100.1.2
    username:   "admin"
    password:   "StormLake21!" 
    

  tasks:
   - name: create user with privs
     ilo_user:
        ilo_ip        : "{{ ip }}"
        ilo_username  : "{{ username }}"
        ilo_password  : "{{ password }}"

        state                       : present       
        data:
          username                  : dhk4
          loginname                 : dhk4
          password                  : new_password
          privileges:
            - LoginPriv                                                    
            - HostBIOSConfigPriv 
            - HostNICConfigPriv                                             
            - HostStorageConfigPriv   
            - RemoteConsolePriv       
            - UserConfigPriv          
            - VirtualMediaPriv        
            - VirtualPowerAndResetPriv
            - iLOConfigPriv                                                   
     register: result
   - debug: var=result['user'] 

