---
- hosts: localhost

  vars:
    username:   "admin"
    password:   "StormLake21!" 
    

  tasks:
   - name: ilo accounts
     ilo_user_facts:
        ilo_ip        : "10.1.1.7"
        ilo_username  : "{{ username }}"
        ilo_password  : "{{ password }}"
        type:       'UserName'
        name: 'dhk'
     no_log: true
     register: result

   - debug: var=result['user']
