---
- hosts: localhost

  vars:
    username:   "admin"
    password:   "some_password" 
    ip:         "some_ip"
    

  tasks:
    - name: Create maintenance window
      ilo_firmware:
        ilo_ip:       '{{ip}}'
        ilo_username: '{{username}}'
        ilo_password: '{{password}}'
    
        state:              present
        option:             Maintenance Window
        data:
          name:           '1st Maintenance window'
          description:    '1st window for maintenance'
          start_time:     'Jul 21 2021 5:00PM'        # Either use long date
          end_time:       '07/22/2021 8:00AM'         # Or use short date

      register: result
    - debug: var=result['ilo']      #['maintenance']
